name: "poseidon:net"
description: >
    FOnline Roleplay Server
about: >
    FOnline Roleplay Server
permalink: /:categories/:year/:month/:day/:title:output_ext

includes_dir: '/'

collections:
  articles:
    output: true

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      category: ''
      subcategory: ''
      layout: "default"

master_repo: false
#url: ""
markdown: kramdown
#redcarpet:
  #extensions: ["tables", "fenced_code_blocks","strikethrough","autolink"]
highlighter: rouge

gems: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 10

logo:             logo.png
disqus_shortname:

rtl: false
